### ISSUE TITLE
Add singleton dimensions

### ISSUE THREAD

**Issue by onetonfoot** [mcabbott/TensorCast.jl#1]
First off thanks for this package it works great! It would be nice if you could also add singleton dimensions, maybe using syntax similar to einops e.g:

```julia

A = rand(5,5,5)

@cast B[a,b,(),c] := A[a,b,c]

size(B) # (5,5,1,5)

```

**Comment by mcabbott** [comment]
Thanks, I hope it's useful. I didn't think of that syntax, but `1` or `_` works:  
```julia
@cast B[a,b,_,c] := A[a,b,c];

size(B) == (5,5,1,5) # true
```
I also just added [a notebook](https://github.com/mcabbott/TensorCast.jl/blob/master/docs/einops.ipynb) copying the einops tutorial.

**Comment by onetonfoot** [comment]
Oh great its already here, actually I think the `_` syntax is a little nicer anyways
