### ISSUE TITLE
Issues with Strided

### ISSUE THREAD

**Issue by MasonProtter** [mcabbott/TensorCast.jl#2]
First, the current tagged version has an issue with `strided`:
```julia
julia> using Strided, TensorCast

julia> A = rand(3,3); B = rand(3,5);

julia> @reduce C[i, j] := sum(l) A[i, l] * B[l, j] strided
ERROR: UndefVarError: strided_permutedims not defined
Stacktrace:
 [1] top-level scope at none:0
```
but that is fixed by moving to master, so I'd recommend tagging a new release.

Second, using `|=` with `strided` returns a view instead of collecting to an array.
```julia
julia> @reduce C[i, j] |= sum(l) A[i, l] * B[l, j] strided
3×5 reshape(::StridedView{Float64,3,Array{Float64,1},typeof(identity)}, 3, 5) with eltype Float64:
 0.308848  0.406922  0.604683  0.240265  0.262697
 0.229795  0.423606  0.431261  0.454207  0.633704
 0.28358   0.41366   0.60017   0.28484   0.274456
```

Thanks for all your work on this wonderful package!

**Comment by mcabbott** [comment]
Thanks for catching that. I've just tagged a new release. And should add tests for Strided at some point. 

Note that `StridedView` is Strided's array type, which is a view of `A.parent`. It does appear to be correctly copied here when using `|=`, in the sense of not being a view of the input, but I agree that it would make sense to produce an ordinary `Array` instead. Will take a look when I have a minute. 

```julia
julia> M = rand(2,2)
2×2 Array{Float64,2}:
 0.905376  0.771094
 0.731114  0.439474

julia> @cast MT[i,j] := M[j,i]  strided
2×2 StridedView{Float64,2,Array{Float64,1},typeof(identity)}:
 0.905376  0.731114
 0.771094  0.439474

julia> MT[1,2] = 33  # this does change M
33

julia> @cast MS[i,j] |= M[j,i]  strided
2×2 StridedView{Float64,2,Array{Float64,1},typeof(identity)}:
 0.905376  33.0     
 0.771094   0.439474

julia> MS[2,1] = 44  # this does not change M
44

julia> M
2×2 Array{Float64,2}:
  0.905376  0.771094
 33.0       0.439474

julia> reshape(MT.parent, 2,2)
2×2 Array{Float64,2}:
  0.905376  0.771094
 33.0       0.439474

julia> reshape(MS.parent, 2,2)  # has been transposed
2×2 Array{Float64,2}:
  0.905376  33.0     
 44.0        0.439474
```

**Comment by MasonProtter** [comment]
One other thing: I have a package that does `using Strided` at the beginning and then later does some reductions with the `strided` option. Everything seems to work fine except that when I load the package I get
```
┌ Error: can't use option strided without using Strided
│   input = "@reduce h[(σˡ, aˡ⁻¹, aˡ), (σˡ′, aˡ⁻¹′, aˡ′)] |= sum(bˡ⁻¹, bˡ)  begin\n    #= /Users/mason/.julia/dev/MatrixProductStates/src/groundstate.jl:33 =#\n    L_ex[bˡ⁻¹, aˡ⁻¹, aˡ⁻¹′] * W[bˡ⁻¹, bˡ, σˡ, σˡ′] * R_ex[bˡ, aˡ, aˡ′]\nend  strided"
└ @ MatrixProductStates ~/.julia/dev/MatrixProductStates/src/groundstate.jl:32
┌ Error: can't use option strided without using Strided
│   input = "@reduce h[(σˡ, aˡ⁻¹, aˡ), (σˡ′, aˡ⁻¹′, aˡ′)] |= sum(bˡ⁻¹, bˡ)  begin\n    #= /Users/mason/.julia/dev/MatrixProductStates/src/groundstate.jl:73 =#\n    L_ex[bˡ⁻¹, aˡ⁻¹, aˡ⁻¹′] * W[bˡ⁻¹, bˡ, σˡ, σˡ′] * R_ex[bˡ, aˡ, aˡ′]\nend  strided"
```
but things still seem to run fine. Any idea what causes this?

I can't seem to cook up a MWE, but the offending package is here: https://github.com/MasonProtter/MatrixProductStates.jl

**Comment by mcabbott** [comment]
This is from some [helpful warnings](https://github.com/mcabbott/TensorCast.jl/blob/master/src/macro.jl#L792) I added based on what packages are loaded, but perhaps I did it wrong or perhaps it's tripping over some issue with conditional loading... and perhaps it's not necessary anyway? For now I've commented this out on master.

**Comment by mcabbott** [comment]
In the current master I changed how `packagecheck` works, would be interested to hear if this re-introduces these warnings for you. Locally it seems fine.

**Comment by mcabbott** [comment]
Added to tests in https://github.com/mcabbott/TensorCast.jl/commit/052998ee6729868b248e44ed2dbe3aa716222996.
