### ISSUE TITLE
Slightly misleading error (DimensionMismatch) when destination is actually not defined

### ISSUE THREAD

**Issue by schneiderfelipe** [mcabbott/TensorCast.jl#30]
Hi @mcabbott! I found the following error (`=` instead of `:=`) to be rather misleading. Instead of a nonexistent destination, the reported error is a `DimensionMismatch`:

```julia
using TensorCast

V = [10, 20, 30]
M = collect(reshape(1:12, 3, 4))

@cast A[j, i] = M[i, j] + 10 * V[i]
# => ERROR: DimensionMismatch("array could not be broadcast to match destination")

@cast A[j, i] := M[i, j] + 10 * V[i]
# => 4×3 Array{Int64,2}:
#     101  202  303
#     104  205  306
#     107  208  309
#     110  211  312
```

Do you think a different error could be thrown in this case?

EDIT:

```julia
(@v1.4) pkg> status TensorCast
Status `~/.julia/environments/v1.4/Project.toml`
  [02d47bb6] TensorCast v0.3.2
```

**Comment by mcabbott** [comment]
Is it possible that `A` already had a value in your session? When I try this cold, I get: 
```
julia> @cast A[j, i] = M[i, j] + 10 * V[i]
ERROR: UndefVarError: A not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/TensorCast/src/macro.jl:214

julia> @cast A[j, i] := M[i, j] + 10 * V[i]
4×3 Matrix{Int64}:
 101  202  303
 104  205  306
 107  208  309
 110  211  312
 ```

**Comment by schneiderfelipe** [comment]
> Is it possible that `A` already had a value in your session? When I try this cold, I get:
> 
> ```
> julia> @cast A[j, i] = M[i, j] + 10 * V[i]
> ERROR: UndefVarError: A not defined
> Stacktrace:
>  [1] top-level scope
>    @ ~/.julia/dev/TensorCast/src/macro.jl:214
> 
> julia> @cast A[j, i] := M[i, j] + 10 * V[i]
> 4×3 Matrix{Int64}:
>  101  202  303
>  104  205  306
>  107  208  309
>  110  211  312
> ```

You're right, my mistake! 🙈
