### ISSUE TITLE
Ternary operator not understood

### ISSUE THREAD

**Issue by darsnack** [mcabbott/TensorCast.jl#35]
The following won't work:
```julia
julia> using TensorCast
[ Info: Precompiling TensorCast [02d47bb6-7ce6-556a-be16-bb1710789e2b]

julia> x = rand(5, 5)
5×5 Array{Float64,2}:
 0.26903    0.601561  0.148919   0.567794   0.287378
 0.0263811  0.899677  0.631467   0.312277   0.927105
 0.932034   0.827717  0.772556   0.7509     0.669956
 0.75523    0.903847  0.0268497  0.964181   0.315231
 0.665162   0.367656  0.9304     0.0565779  0.776945

julia> y = zeros(5, 5)
5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

julia> z = ones(5, 5)
5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

julia> @cast q[i, j] := (x[i, j] > 0.5) ? z[i, j] : y[i, j]
ERROR: TypeError: non-boolean (BitArray{2}) used in boolean context
Stacktrace:
 [1] top-level scope at /Users/darsnack/.julia/packages/TensorCast/rCpV9/src/macro.jl:214
```

For this operation, `@cast` is not really necessary. In practice, my `x`, `y`, and `z` are some sequence of operations where `@cast` is nice to use. I could break up the computation and use `map`, but it would be nice to consistently use TensorCast.jl in my code.

**Comment by mcabbott** [comment]
Right now this is equivalent to `q = @. (x> 0.5) ? z : y`, which gives the same error. What will work is `ifelse`:
```julia
julia> @cast q[i, j] := ifelse(x[i, j] > 0.5, z[i, j],  y[i, j])
5×5 Matrix{Float64}:
 0.0  1.0  0.0  1.0  1.0
 1.0  0.0  1.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  1.0
 0.0  1.0  1.0  1.0  1.0
```
But perhaps your real use has more complicated functions on the right? It might not be hard to detect this, and re-write it as `q = @. ((x,z,y) -> (x> 0.5) ? z : y)(x, z, y)`

**Comment by darsnack** [comment]
> But perhaps your real use has more complicated functions on the right? It might not be hard to detect this, and re-write it as `q = @. ((x,z,y) -> (x> 0.5) ? z : y)(x, z, y)`

Yeah that's my use-case. I use `ifelse` right now, but I think the ternary version would avoid some computation. It's not really a big deal for me, but I figured I'd report it anyways.

**Comment by mcabbott** [comment]
Sure. So the transformation needed is something like this: 
```julia
@cast q[i, j] := (abs(x[i, j]) > 0.5) ? exp(y[i]) : atan(y[i], z[j]+t[j,i])
# q = @. ((x,y,z,t) -> abs(x)>0.5 ? exp(y) : atan(y,z+t))(x, y, z', t')
```
Perhaps:
```julia
julia> @pretty @cast q[i, j] := (abs(x[i, j]) > 0.5) ? exp(y[i]) : atan(y[i], z[j]+t[j,i])
begin
    local quelea = transmute(z, (nothing, 1))
    local shrew = transmute(t, (2, 1))
    local waterbuffalo(x, y, quelea, shrew) = begin
                if abs(x) > 0.5
                    exp(y)
                else
                    atan(y, quelea + shrew)
                end
            end
    q = @__dot__(waterbuffalo(x, y, quelea, shrew))
end
```

**Comment by mcabbott** [comment]
This should be fixed on master. Evil test cases would be welcome, the ones I tested are quite simple:
https://github.com/mcabbott/TensorCast.jl/blob/master/test/four.jl#L44
