### ISSUE TITLE
Friendly request for new tag, for compat

### ISSUE THREAD

**Issue by dehann** [mcabbott/TensorCast.jl#40]
Good day,  

Not sure if it is easily possible to do a new tag at present please...?  I'm finding a difficult compat case in dev work on RoME.jl.  Locally, I can work around it via `TensorCast#master` which includes this commit 62620053 (which allows StaticArrays v1.0).

Dependencies force me to require StaticArrays v1.0, but current TensorCast v0.3.2 unfortunately does not:
https://github.com/mcabbott/TensorCast.jl/blob/03860241fa910f3d3990190c93217f029170c617/Project.toml#L23

**Alternatively**, maybe just a patch release branch for v0.3.3 adding 62620053 (if v0.4.0 is not ready yet)?

This is a great package btw, thanks!

Best,
Dehann

------

xref, JuliaRobotics/RoME.jl#424

```julia
 ERROR: Unsatisfiable requirements detected for package StaticArrays [90137ffa]:
 StaticArrays [90137ffa] log:
 ├─possible versions are: 0.8.0-1.0.1 or uninstalled
 ├─restricted by compatibility requirements with CoordinateTransformations [150eb455] to versions: 0.8.0-1.0.1
 │ └─CoordinateTransformations [150eb455] log:
 │   ├─possible versions are: 0.5.0-0.6.1 or uninstalled
 │   └─restricted to versions 0.5-0.7 by RoME [91fb55c2], leaving only versions 0.5.0-0.6.1
 │     └─RoME [91fb55c2] log:
 │       ├─possible versions are: 0.13.0 or uninstalled
 │       └─RoME [91fb55c2] is fixed to version 0.13.0
 ├─restricted by compatibility requirements with Manifolds [1cead3c2] to versions: 1.0.0-1.0.1
 │ └─Manifolds [1cead3c2] log:
 │   ├─possible versions are: 0.1.0-0.4.20 or uninstalled
 │   └─restricted to versions 0.4.19-0.4 by RoME [91fb55c2], leaving only versions 0.4.19-0.4.20
 │     └─RoME [91fb55c2] log: see above
 └─restricted by compatibility requirements with TensorCast [02d47bb6] to versions: 0.10.0-0.12.5 — no versions left
   └─TensorCast [02d47bb6] log:
     ├─possible versions are: 0.1.0-0.3.2 or uninstalled
     └─restricted to versions 0.2-0.4 by RoME [91fb55c2], leaving only versions 0.2.0-0.3.2
       └─RoME [91fb55c2] log: see above
```

**Comment by mcabbott** [comment]
Hi Dehann, sorry about that, not sure why I didn't tag it after the CompatHelper PR. I can try to do that, I made a branch... 

I was trying to gang all the breaking changes for 0.4 together, but keep finding a few more to add, so it's not quite ready. Although if you do manage to find any sharp corners on master, I would love to know about them.

**Comment by dehann** [comment]
I think that did the trick, thank you very much for the quick reply!  Will post if i see any sharp corners.
