### ISSUE TITLE
Optimization opportunity? 

### ISSUE THREAD

**Issue by MasonProtter** [mcabbott/TensorCast.jl#6]
I don't know how common this is, but the kernel that showed up in this [thread](https://discourse.julialang.org/t/fast-diag-a-b/29363/7): `diag(A'B)` which in TensorCast language would be
```julia
@reduce C[i] := sum(j) A[j, i] * B[j, i]
```
is currently slower than
```julia
dot.(eachcol(A), eachcol(B))
```
(however, we beat that approach if the kernel were `diag(A*B)` instead since `eachrow` is slow )

I think it would be pretty easy to detect this kernel and make it lower to `dot.(eachcol(A), eachcol(B))`.

**Comment by mcabbott** [comment]
Sorry I just saw this. I'm not surprised this is slow, as `@reduce` always broadcasts out to the full array, `dropdims(sum(A .* B, dims=1), dims=1)`, it doesn't go looking for particular patterns. 

However it's possible that `@matmul C[i] := sum(j) A[j, i] * B[j, i]` should be smart enough to produce `diag(A'*B)`, right now it doesn't allow for repeated indices & gives an error. Will take a look when I get around to ironing out the last few bugs in #5.

**Comment by mcabbott** [comment]
Closing as won't-fix, I'm sorry. 

I think the right place for such rules is https://github.com/under-Peter/OMEinsum.jl, which functions by applying manipulations it knows about in sequence.
